" load pathogen
filetype off
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

" set the mapleader key
" let mapleader = "\\"

" set the colorscheme
colorscheme desertEx-cb
"set background=dark
"let g:solarized_termcolors=256
"colorscheme solarized

" filetype detection
if has("autocmd")
	filetype plugin indent on
	autocmd BufEnter * :syntax sync fromstart
endif

" NERDTree settings
let NERDTreeShowHidden=1
let NERDTreeIgnore=['\~$', '\.svn$', '\.git$', '\.swp$']

" Disable supertab for now
let complType=""
syntax on

" Settings
set backspace=indent,eol,start	" Vim under cygin
set number	" display line numbers
set hlsearch	" highlight search matches
set shm=atI	" Disable welcome screen
set ttyfast	" Improves redrawing for newer computers
set nobk nowb noswf	" Disable backup files
set titlestring=%f title	" Display filename in term window
set ruf=%l:%c ruler	" Display column:line bottom right of status line
set showcmd	" Show incomplete command
set ignorecase smartcase	" Only be case sensitive when search has uppercase letters
set mouse=a	" Enable mouse support
set ttymouse=xterm2	" define mouse support type
set enc=utf-8	" Enable utf support
set showmatch matchtime=3	" Cursor briefly returns to matching bracket
set makeprg=php\ -l\ %	" Make php the default lint program
set errorformat=%m\ in\ %f\ on\ line\ %l	" Error format

let php_sql_query=1	" Hilight SQL syntax in strings
let php_htmlInStrings=1	" Hilight HTML in strings
let php_noShortTags=1	" Disable short tags
let php_folding=1	" Enable Folding for classes and functions
