" load pathogen
filetype off
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

" set the mapleader key
" let mapleader = "\\"

" set the colorscheme
colorscheme desertEx-cb

" filetype detection
if has("autocmd")
	filetype plugin indent on
	autocmd BufEnter * :syntax sync fromstart
endif

set backspace=indent,eol,start	" Vim under cygin
set number	" display line numbers
set hlsearch	" highlight search matches
syntax on

